export const SIGNIN_REQUEST_PROCESS = "SIGNIN_REQUEST_PROCESS";
export const SIGNIN_REQUEST_ERROR = "SIGNIN_REQUEST_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const SIGNUP_REQUEST_PROCESS = "SIGNUP_REQUEST_PROCESS";
export const SIGNUP_REQUEST_ERROR = "SIGNUP_REQUEST_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_REQUEST_SUCCESS";

export const LOGOUT = "LOGOUT";
export const REAUTHTOAST = "REAUTHTOAST";

export const USERS_REQUEST_PROCESS = "USERS_REQUEST_PROCESS";
export const USERS_REQUEST_ERROR = "USERS_REQUEST_ERROR";
export const USERS_REQUEST_SUCCESS = "USERS_REQUEST_SUCCESS";
export const USERDEL_REQUEST_ERROR = "USERDEL_REQUEST_ERROR";
export const USERDEL_REQUEST_SUCCESS = "USERDEL_REQUEST_SUCCESS";
export const ROLEUPDATE_REQUEST_ERROR = "ROLEUPDATE_REQUEST_ERROR";
export const ROLEUPDATE_REQUEST_SUCCESS = "ROLEUPDATE_REQUEST_SUCCESS";
export const NAMEUPDATE_REQUEST_ERROR = "NAMEUPDATE_REQUEST_ERROR";
export const NAMEUPDATE_REQUEST_SUCCESS = "NAMEUPDATE_REQUEST_SUCCESS";

export const DEVICES_REQUEST_PROCESS = "DEVICES_REQUEST_PROCESS";
export const DEVICES_REQUEST_ERROR = "DEVICES_REQUEST_ERROR";
export const DEVICES_REQUEST_SUCCESS = "DEVICES_REQUEST_SUCCESS";
export const DEVICEADD_REQUEST_ERROR = "DEVICEADD_REQUEST_ERROR";
export const DEVICEADD_REQUEST_SUCCESS = "DEVICEADD_REQUEST_SUCCESS";
export const DEVICEDEL_REQUEST_ERROR = "DEVICEDEL_REQUEST_ERROR";
export const DEVICEDEL_REQUEST_SUCCESS = "DEVICEDEL_REQUEST_SUCCESS";
export const DEVICEUPDATE_REQUEST_ERROR = "DEVICEUPDATE_REQUEST_ERROR";
export const DEVICEUPDATE_REQUEST_SUCCESS = "DEVICEUPDATE_REQUEST_SUCCESS";

export const UPLOADS_REQUEST_PROCESS = "UPLOADS_REQUEST_PROCESS";
export const UPLOADS_REQUEST_ERROR = "UPLOADS_REQUEST_ERROR";
export const UPLOADS_REQUEST_SUCCESS = "UPLOADS_REQUEST_SUCCESS";
export const UPLOADADD_REQUEST_ERROR = "UPLOADADD_REQUEST_ERROR";
export const UPLOADADD_REQUEST_SUCCESS = "UPLOADADD_REQUEST_SUCCESS";
export const UPLOADDEL_REQUEST_ERROR = "UPLOADDEL_REQUEST_ERROR";
export const UPLOADDEL_REQUEST_SUCCESS = "UPLOADDEL_REQUEST_SUCCESS";
export const UPLOADUPDATE_REQUEST_ERROR = "UPLOADUPDATE_REQUEST_ERROR";
export const UPLOADUPDATE_REQUEST_SUCCESS = "UPLOADUPDATE_REQUEST_SUCCESS";

export const REUSERTOAST = "REUSERTOAST";
export const REDEVICETOAST = "REDEVICETOAST";
export const REUPLOADTOAST = "REUPLOADTOAST";

    